### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [jxnblk/react-geomicons#1]
Would like to add to react.rocks, thanks!

**Comment by jxnblk** [comment]
Cool. They are currently up here, but will make a dedicated demo page in this repo :)
http://jxnblk.com/rebass/docs/components#Icon

**Comment by jxnblk** [comment]
Also please ignore the other stuff on that page – it needs a lot of cleanup.

**Comment by winkler1** [comment]
OK thanks, will do.

**Comment by jxnblk** [comment]
@winkler1 demo should be live: http://jxnblk.com/react-geomicons – let me know if it doesn't work or you have any other suggestions.
