### ISSUE TITLE
Website appears to be down

### ISSUE THREAD

**Issue by theednaffattack** [jxnblk/react-geomicons#10]
Hi Brent,

I don't post issues often so if I'm formatting this wrong please let me know.  The website for react-geomicons appears to be experiencing an error `https://jxnblk.com/bundle.js`.  Just FYI

**Comment by jxnblk** [comment]
Thanks! I don't think I set up all the redirects correctly, but should be live here https://jxnblk.github.io/react-geomicons/

**Comment by theednaffattack** [comment]
Thanks, I really love this library.
