### ISSUE TITLE
Unknown prop `dataId` (library problem)

### ISSUE THREAD

**Issue by lachlanjc** [jxnblk/react-geomicons#5]
This seems to be an internal error with React Geomicons. I was rendering with static-react and from this code:

``` jsx
<Icon name='clock' fill='#758a99' />
```

I got this error:

```
Warning: Unknown prop `dataId` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in svg (created by Icon)
```

(it went on to trace the Icon component up through the DOM hierarchy)

Looks like the `dataId` prop causing an issue is here: https://github.com/jxnblk/react-geomicons/blob/master/src/geomicon.js#L19

@jxnblk if you could take a look at this, that’d be great :wink:

**Comment by wle8300** [comment]
Yarrrrr.. this be throwing "warnings". Yarr.

https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by jxnblk** [comment]
Sorry, I'd started an update, but never wrapped it up. PR here #6

**Comment by wle8300** [comment]
Why aren't you merging the PR?

**Comment by jxnblk** [comment]
@williamle8300 I have a full time job, and I haven't finished the PR yet

**Comment by lachlanjc** [comment]
@jxnblk ✌🏻️

**Comment by jxnblk** [comment]
Should be fixed now. Let me know if you still spot any warnings ✌️

**Comment by lachlanjc** [comment]
💯
